version: 2.1

jobs:
  build_and_push_gem:
    resource_class: small
    docker:
      - image: cimg/ruby:2.7.4
    working_directory: ~/rubocop-amagi
    steps:
      - checkout

      - run:
          name: Compare version
          command: ruby .circleci/compare_version.rb

      - run:
          name: Build Gem
          command: gem build rubocop-amagi.gemspec --output rubocop-amagi.gem

      - run:
          name: Push Gem
          command: |
            gem push rubocop-amagi.gem
workflows:
  version: 2.1
  checks:
    jobs:
      - build_and_push_gem:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
